# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-19 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DemoRequest',
            fields=[
                ('demoRequestId', models.AutoField(db_column='demo_request_id', primary_key=True, serialize=False)),
                ('firstName', models.CharField(db_column='first_name', max_length=25, verbose_name='First name')),
                ('lastName', models.CharField(db_column='last_name', max_length=25, verbose_name='Last name')),
                ('email', models.CharField(db_column='email', max_length=100, verbose_name='Email')),
                ('jobTitle', models.CharField(blank=True, db_column='job_title', max_length=30, null=True, verbose_name='Job title')),
                ('workPhoneNumber', models.CharField(blank=True, db_column='work_phone_number', max_length=15, null=True, verbose_name='Work phone number')),
                ('company', models.CharField(blank=True, db_column='company', max_length=60, null=True, verbose_name='Company')),
                ('message', models.CharField(db_column='message', max_length=5000, verbose_name='Message')),
                ('canReceiveMails', models.BooleanField(db_column='can_receive_mails', default=False, verbose_name='Can receive mails')),
                ('demoRequestCreatedDate', models.DateField(auto_now_add=True, db_column='demo_request_created_date')),
                ('demoRequestUpdatedDate', models.DateField(auto_now=True, db_column='demo_request_updated_date')),
            ],
        ),
    ]
