# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-20 05:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BeyFlowDemoRequests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demorequest',
            name='message',
            field=models.TextField(db_column='message', max_length=5000, verbose_name='Message'),
        ),
    ]
